#!/bin/sh

# Run this script on the dead-mans-switch server with the same period
# as the proof-of-life playbook.  For example, I have Tower running
# the proof-of-life playbook every 5 minutes, and so on the
# dead-mans-switch server I run this script every 5 minutes with cron:
#
# 2,7,12,17,22,27,32,37,42,47,52,57 * * * * /root/check-proof-of-life
#
# I'm using slack for notification here, but pick your poison...

SLACK_WEBHOOK=https://hooks.slack.com/services/[YOUR-WEBHOOK-HERE]

# Has /run/proof-of-life been updated since we last checked?

if [ /run/dead-mans-switch -ot /run/proof-of-life ]; then
  touch /run/dead-mans-switch;
  exit 0;
fi

# Has it not been updated since we last checked?  Something is wrong.

if [ /run/dead-mans-switch -nt /run/proof-of-life ]; then
  curl -X POST -H 'Content-type: application/json' --data '{"text":"ALERT: missing proof-of-life!"}' $SLACK_WEBHOOK
  exit 1;
fi

# Fall through when those files have exactly the same timestamp...


