---
- name: Hit didit endpoint
  hosts: all
  gather_facts: false
  tasks:
    - shell: |
        curl http://34.73.122.192:8080/didit/labdroid/IeLCA1olX74XCqbi5b3nJXn2xRIzmfLPVzOXbFo0UzZg+Pe8gxQYKgD4nARKPMIFVIeIrUFIj0CC
      retries: 3
      delay: 5
